<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/Python-Notebook-Banners/Exercise.png"  style="display: block; margin-left: auto; margin-right: auto;";/>
</div>

# Exercise: Working with DataFrames


In this exercise, we'll be exploring some ways in which we can manipulate the data stored within a Pandas DataFrame.

## Learning objectives

By the end of this train, you should be able to:
* Sort, filter, and group a Pandas DataFrame.
* Create and delete columns in a Pandas DataFrame.
* Transform a Pandas DataFrame.

## Exercises

### Import libraries and dataset

In [1]:
import pandas as pd
import numpy as np

We are using a dataset named `Animals.csv` that stores information about a variety of animal species.

In [2]:
animal_df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/Python/Animals.csv')

In [3]:
animal_df.head()

,Species,Average Lifespan (Years),Habitat,Conservation Status
0,African Elephant,60,Grasslands,Vulnerable
1,Bengal Tiger,15,Forests,Endangered
2,Blue Whale,80,Ocean,Endangered
3,Giant Panda,20,Temperate Forest,Vulnerable
4,Komodo Dragon,30,Islands,Vulnerable

### Exercise 1

Filter the dataset to show only species that have an `Average Lifespan (Years)` **greater than 20** and are classified as `Vulnerable` in `Conservation Status`.

In [4]:
# Your solution here...
animal_df[(animal_df['Average Lifespan (Years)'] > 20) & (animal_df['Conservation Status'] == 'Vulnerable')]

            Species  Average Lifespan (Years)     Habitat Conservation Status
0  African Elephant                        60  Grasslands          Vulnerable
4     Komodo Dragon                        30     Islands          Vulnerable
5        Polar Bear                        25      Arctic          Vulnerable

### Exercise 2

**a)** Create a new column `Lifespan in Months` by converting the `Average Lifespan (Years)` to months.

In [8]:
# Your solution here...
animal_df['Lifespan in Months'] = animal_df['Average Lifespan (Years)'] * 12

animal_df['Lifespan in Months'].head()

0    720
1    180
2    960
3    240
4    360
Name: Lifespan in Months, dtype: int64

**b)** Delete the `Lifespan in Months` column from the DataFrame.

In [9]:
# Your solution here...
animal_df = animal_df.drop('Lifespan in Months', axis=1)

animal_df.head()

,Species,Average Lifespan (Years),Habitat,Conservation Status
0,African Elephant,60,Grasslands,Vulnerable
1,Bengal Tiger,15,Forests,Endangered
2,Blue Whale,80,Ocean,Endangered
3,Giant Panda,20,Temperate Forest,Vulnerable
4,Komodo Dragon,30,Islands,Vulnerable

### Exercise 3

**a)** Filter the DataFrame `animal_df` to include only species with an `Average Lifespan (Years)` **greater than 50 years**. Store the result in a new DataFrame `Long_lived_species`.

In [10]:
# Your solution here...
Long_lived_species_df = animal_df[(animal_df['Average Lifespan (Years)']> 50 )]

Long_lived_species_df.head()

,Species,Average Lifespan (Years),Habitat,Conservation Status
0,African Elephant,60,Grasslands,Vulnerable
2,Blue Whale,80,Ocean,Endangered
13,Green Sea Turtle,80,"Oceans, Beaches",Endangered

**b)** Using the `apply` and `lambda` functions, convert the `Average Lifespan (Years)` of all species into the float data type in `Long_lived_species`.

In [17]:
# Your solution here...
Long_lived_species_df['Average Lifespan (Years)'] = Long_lived_species_df['Average Lifespan (Years)'].apply(lambda x: float(x))

Long_lived_species_df

C:\Users\jeanm\AppData\Local\Temp\ipykernel_80384\4104926898.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Long_lived_species_df['Average Lifespan (Years)'] = Long_lived_species_df['Average Lifespan (Years)'].apply(lambda x: float(x))

,Species,Average Lifespan (Years),Habitat,Conservation Status
0,African Elephant,60.0,Grasslands,Vulnerable
2,Blue Whale,80.0,Ocean,Endangered
13,Green Sea Turtle,80.0,"Oceans, Beaches",Endangered

### Exercise 4

List all columns for species that have the string "`Endangered`" as part of their conservation status.

In [12]:
# Your solution here...
Endangered_species = animal_df[animal_df['Conservation Status'].str.contains('Endangered', na=False)]
Endangered_species.head()

,Species,Average Lifespan (Years),Habitat,Conservation Status
1,Bengal Tiger,15,Forests,Endangered
2,Blue Whale,80,Ocean,Endangered
9,Orangutan,35,Rainforests,Critically Endangered
13,Green Sea Turtle,80,"Oceans, Beaches",Endangered

### Exercise 5

List the mean `Average Lifespan (Years)` of species for each `Habitat` in descending order.

In [21]:
# Your solution here...
Mean_lifespan_by_habitant = animal_df.groupby('Habitat')['Average Lifespan (Years)'].mean().sort_values(ascending=False)

Mean_lifespan_by_habitant

Habitat
Ocean                 80.0
Oceans, Beaches       80.0
Grasslands            60.0
Rainforests           35.0
Islands               30.0
Arctic                25.0
Antarctic             20.0
Forests, Seacoasts    20.0
Temperate Forest      20.0
Forests               15.0
Mountain Ranges       15.0
Savanna               14.0
Eucalyptus Forests    13.0
Forests, Tundra        8.0
Various                5.0
Name: Average Lifespan (Years), dtype: float64

### Exercise 6

Create a column `Threat Level` that categorises species into `High`, `Medium`, or `Low` based on their `Conservation Status`: 
- **High** for `Critically Endangered` and `Endangered` 
- **Medium** for `Vulnerable` and `Near Threatened`
- **Low** for `Least Concern`

In [24]:
# Your solution here...
def categorise_threat(status):
    if status in ['Critically Endagered', 'Endangered_species']:
        return 'High'
    elif status in ['Vulnerable', 'Near Threatened']:
        return 'Medium'
    else:
        return 'Low'
    
animal_df['Threat Level'] = animal_df['Conservation Status'].apply(categorise_threat)

animal_df

,Species,Average Lifespan (Years),Habitat,Conservation Status,Threat Level
0,African Elephant,60,Grasslands,Vulnerable,Medium
1,Bengal Tiger,15,Forests,Endangered,Low
2,Blue Whale,80,Ocean,Endangered,Low
3,Giant Panda,20,Temperate Forest,Vulnerable,Medium
4,Komodo Dragon,30,Islands,Vulnerable,Medium
5,Polar Bear,25,Arctic,Vulnerable,Medium
6,Red Fox,5,Various,Least Concern,Low
7,Emperor Penguin,20,Antarctic,Near Threatened,Medium
8,Koala,13,Eucalyptus Forests,Vulnerable,Medium
9,Orangutan,35,Rainforests,Critically Endangered,Low
10,Snow Leopard,15,Mountain Ranges,Vulnerable,Medium
11,Bald Eagle,20,"Forests, Seacoasts",Least Concern,Low
12,African Lion,14,Savanna,Vulnerable,Medium
13,Green Sea Turtle,80,"Oceans, Beaches",Endangered,Low
14,Gray Wolf,8,"Forests, Tundra",Least Concern,Low

## Solutions

### Exercise 1

In [ ]:
# Filter the DataFrame based on two conditions
filtered_df = animal_df[(animal_df['Average Lifespan (Years)'] > 20) & (animal_df['Conservation Status'] == 'Vulnerable')]

# Display the filtered DataFrame
filtered_df

We filter our DataFrame based on two conditions that are combined using the `&` operator:
- The first part of the condition, `(animal_df['Average Lifespan (Years)'] > 20)`, selects rows where the average lifespan is over 20 years.
- The second part, `(animal_df['Conservation Status'] == 'Vulnerable')`, selects rows where the conservation status is equal to 'Vulnerable'.

### Exercise 2

**a)**

In [ ]:
# Creating 'Lifespan in Months'
animal_df['Lifespan in Months'] = animal_df['Average Lifespan (Years)'] * 12
animal_df

We add a new column named `Lifespan in Months` calculated by multiplying each value in `Average Lifespan (Years)` by 12 to convert from years to months.

**b)**

In [ ]:
# Deleting 'Lifespan in Months'
animal_df.drop('Lifespan in Months', axis=1, inplace=True)
animal_df

We remove the newly created `Lifespan in Months` from the DataFrame using the `drop` method. `axis=1` indicates the deletion of a column while `inplace=True` is used to ensure that the change is applied directly to `animal_df`.

### Exercise 3

**a)**

In [15]:
# Filtering to find long-lived species whose 'Average Lifespan (Years)' is greater than 50 years.
Long_lived_species = animal_df[animal_df['Average Lifespan (Years)'] > 50]

# Display the filtered DataFrame
Long_lived_species

,Species,Average Lifespan (Years),Habitat,Conservation Status
0,African Elephant,60,Grasslands,Vulnerable
2,Blue Whale,80,Ocean,Endangered
13,Green Sea Turtle,80,"Oceans, Beaches",Endangered

**b)**

In [16]:
# Transform the Average Lifespan (Years) column to the floats
Long_lived_species['Average Lifespan (Years)'] = Long_lived_species['Average Lifespan (Years)'].apply(lambda x: float(x))

# Display the updated DataFrame 
Long_lived_species

C:\Users\jeanm\AppData\Local\Temp\ipykernel_80384\309533859.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Long_lived_species['Average Lifespan (Years)'] = Long_lived_species['Average Lifespan (Years)'].apply(lambda x: float(x))

,Species,Average Lifespan (Years),Habitat,Conservation Status
0,African Elephant,60.0,Grasslands,Vulnerable
2,Blue Whale,80.0,Ocean,Endangered
13,Green Sea Turtle,80.0,"Oceans, Beaches",Endangered

We use a **lambda** function to **apply** the operation of converting to float across all values in the `Average Lifespan (Years)` column in the `Long_lived_species` DataFrame.

### Exercise 4

In [ ]:
# Filtering to find species with 'Endangered' in their conservation status
Endangered_species = animal_df[animal_df['Conservation Status'].str.contains('Endangered')]

# Display the filtered DataFrame
Endangered_species

We use the method `.str.contains('Endangered')` to identify species whose `Conservation Status` contains the substring `Endangered`. 
The result is stored in a new DataFrame, `Endangered_species`.

### Exercise 5

In [19]:
Mean_lifespan_by_habitat = animal_df.groupby('Habitat')['Average Lifespan (Years)'].mean().sort_values(ascending=False)

Mean_lifespan_by_habitat

Habitat
Ocean                 80.0
Oceans, Beaches       80.0
Grasslands            60.0
Rainforests           35.0
Islands               30.0
Arctic                25.0
Antarctic             20.0
Forests, Seacoasts    20.0
Temperate Forest      20.0
Forests               15.0
Mountain Ranges       15.0
Savanna               14.0
Eucalyptus Forests    13.0
Forests, Tundra        8.0
Various                5.0
Name: Average Lifespan (Years), dtype: float64

The `groupby('Habitat')` groups the data in the DataFrame `animal_df`, where each group corresponds to a unique habitat.

Within each group, the `.mean()` method is applied to find the average lifespan of species within that habitat.

The `sort_values(ascending=False)` method then sorts these average values in descending order.

### Exercise 6

In [ ]:
# Function to categorise species based on their conservation status.
def categorise_threat(status):
    if status in ['Critically Endangered', 'Endangered']:
        return 'High'
    elif status in ['Vulnerable', 'Near Threatened']:
        return 'Medium'
    else:
        return 'Low'
# Apply the 'categorise_threat' function to the 'Conservation Status' column
animal_df['Threat Level'] = animal_df['Conservation Status'].apply(categorise_threat)

animal_df

We define the `categorise_threat` function which uses conditional statements to categorise species based on their conservation status.

We then use the `apply` method to apply the function to each row in the `Conservation Status` column.

The results are stored in a new column, `Threat Level`.

<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/refs/heads/master/ALX_banners/ALX_Navy.png"  style="width:140px";/>
</div>